//Auth action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_STATUS = "AUTH_STATUS";

//Products action types
export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";
export const PRODUCT_FETCH_NOT_NEEDED = "PRODUCT_FETCH_NOT_NEEDED";

//Cart action types
export const CART_RELOADED = "CART_RELOADED";

//Category action types
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const CATEGORY_FETCH_START = "CATEGORY_FETCH_START";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";

export const CATEGORY_UPDATE_START = "CATEGORY_UPDATE_START";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const SET_ID_FOR_UPDATE = "SET_ID_FOR_UPDATE";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
export const CATEGORY_DELETE_START = "CATEGORY_DELETE_START";
